### ISSUE TITLE
建议 发送文件/图片/视频 从emoji改回原来的send/发送 

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#107]
建议 
发送文件/图片/视频 从emoji改回原来的send/发送

起因
因为tg一直不支持中文搜索,也不知道emoji搜索
wechat group的内容无法指定到具体个人
原本的提示语 可以通过检索 
昵称: sent a picture.  昵称: 发送图片。
等形式来检索 具体的某一个人的某一项行为
但是现在更改为emoji后.
导致只能具体检索 某一个人 而 无法具体到某一项行为

具体示例如下
原本提示语
![image](https://user-images.githubusercontent.com/9905297/88483243-338c4c80-cf99-11ea-9c01-68a1031503ea.png)
![image](https://user-images.githubusercontent.com/9905297/88483235-253e3080-cf99-11ea-9c2a-d86845fff625.png)

更换为emoji后
![image](https://user-images.githubusercontent.com/9905297/88483273-5880bf80-cf99-11ea-9440-8dbbac1bb44c.png)
emoji的形式导致 无法 指定某一项行为
给检索带来了更大的不变.

**Comment by blueset** [comment]
Fixed in blueset/efb-telegram-master#104.
