### ISSUE TITLE
无法转发多条公众号信息

### ISSUE THREAD

**Issue by lzybetter** [blueset/efb-wechat-slave#13]
使用最新版的微信从端无法转发多条公众号消息，如果公众号同时推送多条消息，只能转发第一条，并且会报一下错误。不知道是不是我的设置错误。

```
File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/slave_message.py", line 51, in wrap_functions
logger.debug("[%s] Raw message: %r", msg.id, msg.raw)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by blueset** [comment]
方便提供一下关于这条消息的完整 Verbose Log 吗？

**Comment by wolfsilver** [comment]
https://github.com/blueset/efb-wechat-slave/blob/4fe1667f09f1ef661cef7adda0a7da428b95797d/efb_wechat_slave/slave_message.py#L179-L180

感觉是这个地方有问题，第一条之后的消息丢失了会话信息

**Comment by lzybetter** [comment]
不好意思，之前没有来及时回复，是需要这个记录么
![qq 20180318140937](https://user-images.githubusercontent.com/18044424/37601133-3ff6ca0c-2bc4-11e8-8cd5-a68d159ec70d.jpg)

**Comment by blueset** [comment]
是在复现该 bug 过程中**完整**的 **verbose** 日志。

**Comment by lzybetter** [comment]
不好意思，我是个小白，你说的这个我应该去哪里找呢

**Comment by blueset** [comment]
已尝试于 e6f7d63 修复
