### ISSUE TITLE
获取头像崩溃

### ISSUE THREAD

**Issue by mlch911** [blueset/efb-wechat-slave#139]
https://github.com/ehForwarderBot/efb-wechat-slave/blob/80dadf21558c1be28d7ec23f247383b5a229975b/efb_wechat_slave/__init__.py#L561
这行代码会在获取头像失败时抛出异常，但如果聊天对象确实没有设置头像，也会走到这里。

**Comment by blueset** [comment]
这是预期行为。详细说明请参见文档。
https://ehforwarderbot.readthedocs.io/zh_CN/latest/API/channel.html#ehforwarderbot.channel.SlaveChannel.get_chat_picture
