### ISSUE TITLE
微信转发的消息可否带上telegram的username

### ISSUE THREAD

**Issue by TimeLordFang** [blueset/efb-wechat-slave#14]
想做一个双向转发的功能，也就是微信号也当做一个bot来用。
把telegram机器人link到群里之后，把群里所有人加到admin列表，然后bot可以转发所有人的消息到微信，但是只能由一个微信号发，所以微信在转发的时候取到telegram的username加到消息头上

可以做一个这样的可选功能吗，或者如果简单的话能指点一下具体修改哪一块的代码，我自己试试

**Comment by blueset** [comment]
处于安全考虑，不建议将不信任的人添加到管理员列表，因为所有管理员都可以拥有当前启用所有从端的所有权限。依照框架设计，群组同步功能建议独立成为一个主端，并使其同步所有指定从端会话的消息内容。

相关设想请参见 [这篇博客](https://blog.1a23.com/2017/01/28/Idea-Group-Chat-Tunneling-Sync-with-EH-Forwarder-Bot/) 。

**Comment by jasondong1999** [comment]
我想要转发群里一个机器人的消息，但是我将那个机器人的ID添加到管理员列表不起作用，普通用户转发就没问题

**Comment by blueset** [comment]
> 我想要转发群里一个机器人的消息，但是我将那个机器人的ID添加到管理员列表不起作用，普通用户转发就没问题

Telegram API 由于设计原因阻止了 bot 之间互相收发消息。转发其他 Telegram bot 消息的功能故无法实现。

**Comment by jasondong1999** [comment]
谢谢你的解答，但是群里的机器人并不是给ehFbot私发消息啊，只是在群里发布了消息，ehFbot不是可以读取群里的消息吗？

**Comment by blueset** [comment]
> 谢谢你的解答，但是群里的机器人并不是给ehFbot私发消息啊，只是在群里发布了消息，ehFbot不是可以读取群里的消息吗？ 因为我使用这个机器人目的就是想要转发该机器人的信息，因为这个信息比较重要，有时候没有上TG就无法看到该信息，而且该信息是有时效性的

前述限制适用于任何 bot 与 bot 间的通讯，无论是私聊还是群组消息。若另外的 bot 是阁下运营的话，可以尝试改写 bot 代码并接入 EFB 中间件。

**Comment by jasondong1999** [comment]
> > 谢谢你的解答，但是群里的机器人并不是给ehFbot私发消息啊，只是在群里发布了消息，ehFbot不是可以读取群里的消息吗？ 因为我使用这个机器人目的就是想要转发该机器人的信息，因为这个信息比较重要，有时候没有上TG就无法看到该信息，而且该信息是有时效性的
> 
> 前述限制适用于任何 bot 与 bot 间的通讯，无论是私聊还是群组消息。若另外的 bot 是阁下运营的话，可以尝试改写 bot 代码并接入 EFB 中间件。

您好，另外一个BOT是@junction_bot，是一个频道消息转发的机器人，其实我就是想把一个公开频道的消息转发到我的微信上，我可以做到吗？或者不通过@junction_bot，直接用ehFbot呢？

**Comment by blueset** [comment]
> > > 谢谢你的解答，但是群里的机器人并不是给ehFbot私发消息啊，只是在群里发布了消息，ehFbot不是可以读取群里的消息吗？ 因为我使用这个机器人目的就是想要转发该机器人的信息，因为这个信息比较重要，有时候没有上TG就无法看到该信息，而且该信息是有时效性的
> > 
> > 
> > 前述限制适用于任何 bot 与 bot 间的通讯，无论是私聊还是群组消息。若另外的 bot 是阁下运营的话，可以尝试改写 bot 代码并接入 EFB 中间件。
> 
> 您好，另外一个BOT是@junction_bot，是一个频道消息转发的机器人，其实我就是想把一个公开频道的消息转发到我的微信上，我可以做到吗？或者不通过@junction_bot，直接用ehFbot呢？

如果只是这样的话，手写一个 user bot 把频道的消息转发过来应该也不难。User bot 的特点是它可以利用普通账号，而不受 Telegram Bot API 的局限。

**Comment by jasondong1999** [comment]
太感谢了，我通过人行自走的解决了，谢谢
