### ISSUE TITLE
[FR] Is there an existing implementation which can replace the content of the message being sent?

### ISSUE THREAD

**Issue by realdeveloperongithub** [blueset/efb-wechat-slave#140]
## Is your feature request related to a problem? Please describe. 您的建议具体与什么有关？  
I'd like to replace some keywords of the message being sent from the slave, is there an existing implementation of it?

## Describe the solution you'd like 希望的解决方案
I tried to look into the code but i found no replacement of the message being sent.

## Describe alternatives you've considered 考虑过的替代方案  

##Additional context 补充内容

**Comment by blueset** [comment]
You can write a middleware to achieve this. 
* [Learn more about middlewares](https://ehforwarderbot.readthedocs.io/en/latest/guide/walkthrough.html#middlewares)
* [Check out existing middlewares](https://github.com/ehForwarderBot/ehForwarderBot/wiki/Modules-Repository#middlewares)
