### ISSUE TITLE
[BUG] EWS & ETM：批量绑定 启动REPL模式没有>>>出现

### ISSUE THREAD

**Issue by okwellok** [blueset/efb-wechat-slave#144]
### 版本信息 Version Info

```
EH Forwarder Bot
Version: 2.1.1
Python version:
3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
Running on profile "wechat".

Master channel:
    Telegram Master (blueset.telegram) 2.3.1 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.7 # Default instance

Middlewares:
    Link Preview Middleware (catbaron.link_preview) 0.1.0 # Default instance
    Search Message Middleware (catbaron.search_msg) 0.1.0 # Default instance
    MP InstantView Middleware (catbaron.mp_instantview) 0.3.2 # Default instance
```

### 问题描述 Describe the bug

按照wiki批量绑定的第三步，执行`python3 -i -m ehforwarderbot -p wechat`时，没有进入REPL模式，也没出现预期的>>>。按Ctrl+c，之后出现了>>>但是执行完命令之后没有任何反应，重启服务也是。
### 重现步骤 To Reproduce

在当前的 profile 中设置 ETM 为主端，并启用 EWS，执行`python3 -i -m ehforwarderbot -p wechat`
### 截图 Screenshots

![图片](https://user-images.githubusercontent.com/83217712/208342958-f71292b1-0862-45e4-958b-13f4b3630107.png)

### Verbose 日志 Log
<details>
<summary>Verbose 日志</summary>

```
请在下方贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。

【贴在下面】



【贴在上面】

```
 
</details>

**Comment by blueset** [comment]
该文章所述内容可能由于过于久远而已失效。

**Comment by grrushy** [comment]
请问现在有命令进行批量绑定吗？
