### ISSUE TITLE
EWS 连续接收文件时收到均为同一文件

### ISSUE THREAD

**Issue by NWindy5** [blueset/efb-wechat-slave#22]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b10
Python version:
3.6.3 (default, Oct  6 2017, 08:44:35)
[GCC 5.4.0 20160609]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b11 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a12

Middlewares:
    No middleware is enabled.

### 问题描述

连续发送多个文件时同一个文件被命名多次发送到 Telegram 中
即最终虽然看上去接受到了所有的文件, 但是都是一个文件(大小都完全一样)

### 重现步骤

同时(快速)发送多个文件

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
已通过 Telegram 发送



```
 
</details>

**Comment by blueset** [comment]
由 itchat 引起的问题。

(fix by #29 #30)

**Comment by blueset** [comment]
已通过 #29 修复。

**Comment by zhou13** [comment]
好像我依然有这个问题。
