### ISSUE TITLE
微信端收到多条语音，且后续语音时长较长时，efb有几率只发出第一条消息

### ISSUE THREAD

**Issue by leavesster** [blueset/efb-wechat-slave#28]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b11
Python version:
3.6.6 (default, Jun 28 2018, 04:42:43)
[GCC 5.4.0 20160609]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b12 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a13 # Default profile

Middlewares:
    No middleware is enabled.

### 问题描述

微信端连续收到多条语音，且后续语音时长较长时，telegram上有几率只收到第一条。（较为容易复现）

### 重现步骤

1. 从微信端，先发一条语音（1至2秒）。
1. 然后立刻发送第二条语音，并且时间长一些（8至9秒）。

此时有几率只收到前一条，后一条丢失。
第二条语音的时间需要比较长，不能简单的只发一两秒。

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by blueset** [comment]
我尝试在这边的环境里面重复了 10 次，上述操作，没能狗成功复现该问题。

如果可能的话希望提供一下完整复现过程的 Verbose 日志。谢谢。

**Comment by leavesster** [comment]
暂时无法提供复现的 verbose log。
可能跟语音无关，只是 `从微信连续几条消息会丢` 这个 bug 的一种体现而已。
我会打开 verbose log 后运行 efb，到时候再出现类似情况，再新开 issue 提供 log。
谢谢。
