### ISSUE TITLE
重新登录后丢失大量 link

### ISSUE THREAD

**Issue by AkazaDorian** [blueset/efb-wechat-slave#32]
包括重启和掉线直接重连，尝试过替换回之前备份的 tgdata.db 也没有用。早些时候 link 的联系人和群组不会丢失，丢失的都是最近半个月新 link 的。

**Comment by AkazaDorian** [comment]
测试了一下，删除 tgdata.db 之后重新 link 得到的文件大小在 30k 左右，而之前的文件大概有 8m，会不会是这个原因呢？

**Comment by yongman** [comment]
I also have this issue. After restart efb, some latest links will be lost. @blueset

**Comment by lgcde** [comment]
重登之后tgdata.db里的slavechatinfo表会生成新的lave_chat_name同名纪录,但是新的slave_chat_uid改变了.
chatassoc表里绑定的slave_uid没有随之改变,导致之前的link失效
临时解决办法:使用[sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser/releases)手动批量修改tgdata.db

**Comment by blueset** [comment]
待尝试的的解决方案：在新 puid 生成的时候异步+延迟写入 puid.pkl。

**Comment by theFool32** [comment]
有新进展或者其他妥协方案吗。
目前发现重新 link 到原来的群组， 能接收消息，但发送消息似乎是有两个目标。

**Comment by blueset** [comment]
异步延迟写入的方案已推送更新。目前具体的导致 PUID 匹配失败原因仍未能够找到。

顺便在这里也说明一下：
所谓「掉绑定」现象造成的原因是因为上游库 `wxpy` 的 PUID 生成机制不稳定。

网页版微信的接口没有提供会话的永久唯一 ID，而是在每次登录时为会话随机分配一个临时 ID 用于识别。这个临时 ID 在每次重新登录之后都会随机分配。

由于这种干扰措施的存在，我们只能通过会话中的其他信息来为其自行安排伪永久 ID。

wxpy 使用了会话的名称、性别（若有）、省份（若有）、城市（若有）这四个属性点组合来尝试匹配会话并分配新的伪永久 ID —— PUID。

由于未知的原因，wxpy 会在一些情况下无法为本应有匹配的会话匹配出 PUID。这些会话被认为是新的会话，并被分配上了新的 PUID。因此，主端会认为这些会话是新的会话、并区别对待。

综上所述、关于所谓「掉绑定」、或 PUID 匹配问题，仅是 PUID 管理部分发生的问题，与主端无关。

相关代码存在于 [puid_map.py](https://github.com/blueset/efb-wechat-slave/blob/master/efb_wechat_slave/wxpy/utils/puid_map.py)。

**Comment by blueset** [comment]
2.0.0a17 新增了 [PUID 追踪日志][readme]选项。

有意愿协助调试的用户可以通过将 `puid_logs` 实验选项设置为任意文件的绝对路径来开启本日志功能。在发生异常现象之后将日志直接发送给我，或使用我的 GPG 公钥加密后上传到这里。

注意：
- PUID 日志可能会根据会话数量和消息吞吐量的不同而占用大量存储空间。
- PUID 日志包含微信会话（私聊、群组、群成员）相关信息。启用后默认所有日志均保存于本地，但请确保运行环境的安全。

[readme]: https://github.com/blueset/efb-wechat-slave#%E5%AE%9E%E9%AA%8C%E5%8A%9F%E8%83%BD

**Comment by theFool32** [comment]
希望添加 /unlink 功能。
link 到某一 group 后，由于意外丢失 link, 但是之前的 link 其实还在，重新 link 回该 group, 会导致无法在这个 group 中直接发消息。目前只能删掉 group 重新建。
希望能有更好的方式。

**Comment by blueset** [comment]
@theFool32 该功能属于 [ETM][etm]，而非本项目。

----

顺便，在 Telegram 群组内发送 `/link` 即可查看并管理当前 Telegram 群组绑定。

[etm]: https://etm.1a23.studio

**Comment by AkazaDorian** [comment]
不知道能不能给群组也生成一个 PUID 呢？比如每隔一小时 update 一次群组名，掉线之后重新 link 对应的群组，这样应该可以保证大部分情况下群组可以重新 link 上

**Comment by blueset** [comment]
@AkazaDorian 「会话」已经包括了私聊、群聊、公众号、特殊账号等。

**Comment by AkazaDorian** [comment]
@blueset 好的，萬分感謝

**Comment by AkazaDorian** [comment]
测试了一周感觉群组重连的成功率很低，是需要什么特殊操作吗？重装之类的？

**Comment by kettly1260** [comment]
@blueset @lgcde 请问 微信里面的新闻推送为什么没办法link呢？搜索不到这个

**Comment by blueset** [comment]
@kettly1260 「新闻推送」指的是哪种消息？

**Comment by kettly1260** [comment]
> @kettly1260 「新闻推送」指的是哪种消息？

@blueset 就是腾讯新闻。link的时候搜索不到

**Comment by blueset** [comment]
近五个月内没有发现 PUID 信息丢失或匹配失败的情况。若此后仍无相关汇报，此 issue 将会被标记为「过时」并被关闭。

**Comment by blueset** [comment]
@kettly1260 系统特殊账号的支持目前仅包括了文件传输助手。之后会有计划允许用户选择启用的系统账号会话支持。参见 #57。
