### ISSUE TITLE
不能提示添加好友的请求？

### ISSUE THREAD

**Issue by blueset** [blueset/efb-wechat-slave#4]
_From @wolfsilver on October 29, 2017 10:54_

不能提示添加好友的请求？
网页版是可用收到请求的

_Copied from original issue: blueset/ehForwarderBot#92_

**Comment by blueset** [comment]
这个功能是有做出来的。不知你那边是具体什么症状？

**Comment by blueset** [comment]
_From @wolfsilver on November 3, 2017 11:2_

收不到请求，只能在手机上看到请求，

![image](https://user-images.githubusercontent.com/2452450/32370946-df3ef3d4-c0c9-11e7-9bf3-b7ba8d8601a0.png)


我这把Useless的类型去掉了，应该不影响吧

**Comment by blueset** [comment]
_From @wolfsilver on November 3, 2017 11:18_

我这号也已经废了，不能用Web微信了。。

**Comment by wolfsilver** [comment]
可能是itchat有更改，我改了下，貌似收到请求了

https://github.com/wolfsilver/ehForwarderBot/blob/master/plugins/eh_wechat_slave.py#L578

```
        # tdict.update(msg['Text']['userInfo'])
        tdict.update(msg['Text']['autoUpdate'])
```

**Comment by blueset** [comment]
EWS v2 目前没有出现这段代码，但其可用性有待验证。

**Comment by blueset** [comment]
Marking this issue as stale and closing as this is out of date.
