### ISSUE TITLE
无法发送图片（错误 1101）

### ISSUE THREAD

**Issue by blueset** [blueset/efb-wechat-slave#47]
自 2019 年 4 月 29 日起，陆续有用户报告发送图片失败，提示错误代码 1101。该错误同时出现其他非 EWS 用户、甚至一般网页版微信用户当中。

我们初步猜测是微信方面做出的限制。

我们可能将在未来对此特例进行错误信息的优化，以及其他改进。

### 参阅
- [Fwolf @ EFB Support Group](https://t.me/c/1083959736/51616)
- [jazzBob @ EFB Support Group](https://t.me/c/1083959736/51631)
- [littlecoder/itchat#820](https://github.com/littlecodersh/ItChat/issues/820)

**Comment by alexsamtw** [comment]
谢谢您的回覆

**Comment by newdee** [comment]
确实如此，期待解决

**Comment by alexsamtw** [comment]
刚才测试jpg已可以成功传送，包含网页版也是

**Comment by newdee** [comment]
> 刚才测试jpg已可以成功传送，包含网页版也是

确实，但是贴纸表情依然无法发送

**Comment by ilpl** [comment]
大家都有这个问题 , 那我就放心了
