### ISSUE TITLE
部分微信会话不能添加到group回复

### ISSUE THREAD

**Issue by galenzhao** [blueset/efb-wechat-slave#54]
发现同一个telegram和微信salve，
有些微信中的回话在link到group之后，
无法在telegram中回复消息，
提示错误：
Message is not sent.

ResponseError('err_code: 1; err_msg: ',)

但是直接reply消息是可以发送成功

**Comment by blueset** [comment]
此错误提示是来自 Web WC 的错误提示。意义、导致原因、以及解决方法不明。

**Comment by blueset** [comment]
Duplicate of #40
