### ISSUE TITLE
无法使用 /update_info

### ISSUE THREAD

**Issue by bao3** [blueset/efb-wechat-slave#59]
### 版本信息
EFB 2.0 b15

### 问题描述
使用 /update_info 刷新头像时，得到提示：
`Error occurred while update chat information.Not enough rights to change chat title` 

在几个 Group 里都尝试过，一样有问题，于是查看服务器，得到如下信息：

```
handler.handle_update(update, self)                                                     
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in
 handle_update                                                                              
    return self.callback(dispatcher.bot, update, **optional_args)                           
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/commands.py", line 132, i
n extra_listing                                                                             
    msg += "\n\n<b>%s %s (%s)</b>" % (i.channel_emoji, i.module_name, i.module_id)          
AttributeError: 'WeChatChannel' object has no attribute 'module_name'                

```

### 重现步骤

在 telegram 的聊天框里输入 /update_info 

```
 
</details>

**Comment by blueset** [comment]
*属于 EFB Telegram 主端（ETM）相关的提问。*

请仔细阅读提示内容：「Error occurred while update chat information. **Not enough rights to change chat title.** 」请确保您的 ETM Telegram Bot 拥有适当的群管理员权限。

**Comment by bao3** [comment]
重开此 issue 
Telegram bot 已经是 admin 权限。执行 `/update_info` ，这次没有任何 python 错误，只是在  telegram 相应的 group 里，会提示 ：

>/update_info@testwechat_bot
>该指令只适用于单一绑定的群组。目前该群组已绑定了 0 个会话。
>
>

不过实际上我的这个 bot 绑定了很多 group 。。。。
