### ISSUE TITLE
希望加入删除消息功能

### ISSUE THREAD

**Issue by wsndshx** [blueset/efb-wechat-slave#63]
### 版本信息
![image](https://user-images.githubusercontent.com/7829265/62462023-eaa41c80-b7b8-11e9-9e26-1759ea5d5893.png)
使用实验性功能实现了消息的修改，那能不能实现消息的纯撤回呢？

**Comment by blueset** [comment]
EWS 是有实现消息撤回接口的，可以直接使用。

**Comment by kettly1260** [comment]
@catbaron0 想请教一下怎么使用实验性功能啊

**Comment by catbaron0** [comment]
> @catbaron0 想请教一下怎么使用实验性功能啊

在 `$HOME/.ehforwarderbot/profiles/default/blueset.wechat/config.yaml` 添加。
参考 https://github.com/blueset/efb-wechat-slave#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BE%8B

**Comment by kettly1260** [comment]
> > @catbaron0 想请教一下怎么使用实验性功能啊
> 
> 在 `$HOME/.ehforwarderbot/profiles/default/blueset.wechat/config.yaml` 添加。
> 参考 https://github.com/blueset/efb-wechat-slave#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BE%8B

这个文件是需要自己创建是吗

**Comment by catbaron0** [comment]
> > > @catbaron0 想请教一下怎么使用实验性功能啊
> > 
> > 
> > 在 `$HOME/.ehforwarderbot/profiles/default/blueset.wechat/config.yaml` 添加。
> > 参考 https://github.com/blueset/efb-wechat-slave#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BE%8B
> 
> 这个文件是需要自己创建是吗

如果没有就自己创建一个。另外这个目录是普通环境中的默认的配置文件路径，相同路径下应该有 `wxpy.pkl` 和 `wxpy_puid.pkl` 两个文件，如果没有那可能是在别的地方（特别是如果你用 Docker 的话）

**Comment by kettly1260** [comment]
> > > > @catbaron0 想请教一下怎么使用实验性功能啊
> > > 
> > > 
> > > 在 `$HOME/.ehforwarderbot/profiles/default/blueset.wechat/config.yaml` 添加。
> > > 参考 https://github.com/blueset/efb-wechat-slave#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BE%8B
> > 
> > 
> > 这个文件是需要自己创建是吗
> 
> 如果没有就自己创建一个。另外这个目录是普通环境中的默认的配置文件路径，相同路径下应该有 `wxpy.pkl` 和 `wxpy_puid.pkl` 两个文件，如果没有那可能是在别的地方（特别是如果你用 Docker 的话）

好的。那个纯撤回你弄好了吗

**Comment by catbaron0** [comment]
@kettly1260 打开 `delete_on_edit` 开关，把要撤回的消息编辑为 ``rm` ``即可。
我记得这个命令在 1.0 里面是可以编辑的，当前版本的文档中似乎把这个功能的说明移除了？

**Comment by blueset** [comment]
> 当前版本的文档中似乎把这个功能的说明移除了？

有的呃……

[原文](https://github.com/blueset/efb-telegram-master/#edit-and-delete-message)，[简中翻译](https://github.com/blueset/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#%E7%BC%96%E8%BE%91%E5%92%8C%E5%88%A0%E9%99%A4%E6%B6%88%E6%81%AF)。

**Comment by catbaron0** [comment]
> > @catbaron0
> > 当前版本的文档中似乎把这个功能的说明移除了？
> 
> 有的呃……
> 
> [原文](https://github.com/blueset/efb-telegram-master/#edit-and-delete-message)，[简中翻译](https://github.com/blueset/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#%E7%BC%96%E8%BE%91%E5%92%8C%E5%88%A0%E9%99%A4%E6%B6%88%E6%81%AF)。

哦 我记成是 EWS 中的说明了……抱歉
