### ISSUE TITLE
无法在数据库中找到该消息  UC03

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#64]
efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:84)
    Error occurred while processing message from slave channel.
Message: <EFBMsg, <EFBChat: You (__self__) @ WeChat Slave>@<EFBChat: 桜 (him, 08c716c8) @ WeChat Slave> [Text]: 1; Attributes: None; Delivering to: <efb_telegram_master.TelegramChannel object at 0x7fc9957fc160>; Edited: False; System message: False; Substitutions: None; Target messages: None; UID: 425045152345127060; Reactions: {}; File: None (None @ None), None; Vendor: {}>
TypeError("can't pickle _thread.lock objects")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/efb_telegram_master/slave_message.py", line 81, in send_message
    self.dispatch_message(msg, msg_template, old_msg_id, tg_dest)
  File "/usr/local/lib/python3.7/dist-packages/efb_telegram_master/slave_message.py", line 189, in dispatch_message
    "pickle": pickle.dumps(etm_msg)
TypeError: can't pickle _thread.lock objects

### 问题描述
无法在数据库中找到该消息。
请对另一条消息重试。(UC03)
凡是直接和bot对话
都无法回复

### Verbose 日志
This is EFB Telegram Master Channel 2.0.0b24.dev1, running on EFB 2.0.0b17.
1 slave channel activated:
- 💬 WeChat Slave (blueset.wechat, <module 'efb_wechat_slave.__version__' from '/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/__version__.py'>)
```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by blueset** [comment]
已知问题，已解决，待发布。

**Comment by blueset** [comment]
已发布修复。

**Comment by shzxm** [comment]
辛苦了
