### ISSUE TITLE
update_info无法更改头像

### ISSUE THREAD

**Issue by oocococo** [blueset/efb-wechat-slave#68]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b19
Python version:
3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b25 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a28 # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述

绑定联系人到群聊并给予机器人admin权限后使用update_info，提示“绑定的从端不存在。”，group的名称被成功更改，但是没有群聊的头像没有改。

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by blueset** [comment]
请提供相关过程的完整 verbose 日志，谢谢。

**Comment by oocococo** [comment]
2019-09-06 11:20:55,161 [DEBUG]: telegram.ext.dispatcher (dispatcher.start; dispatcher.py:227)
    Processing Update: {'update_id': 57531115, 'message': {'message_id': 262, 'date': 1567768854, 'chat': {'id': -1001375053364, 'type': 'supergroup', 'title': '💬👤 XXX'}, 'text': '/update_info@XXXbot', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 20}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': XXX, 'first_name': 'XXX', 'is_bot': False, 'last_name': '🅥', 'username': 'XXX', 'language_code': 'zh-hans'}}}
2019-09-06 11:20:55,161 [DEBUG]: efb_telegram_master.locale_handler (locale_handler.check_update; locale_handler.py:41)
    [57531115] Update has language zh-hans.
2019-09-06 11:20:55,417 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2937)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."master_uid" = ?)', ['blueset.telegram -1001375053364'])
2019-09-06 11:20:55,429 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2937)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."slave_uid" = ?)', ['blueset.wechat fb4e7885'])

**Comment by blueset** [comment]
已发布。
