### ISSUE TITLE
功能请求: 使用inline queries功能发送表情

### ISSUE THREAD

**Issue by monologconnor** [blueset/efb-wechat-slave#71]
你好
telegram官方的sticker bot有表情任意一边必须为512像素的限制, 且微信上个人使用的表情包大多小于512x512的尺寸, 因此想到能不能在forwarderbot上加上inline queries的功能, 使用户能在服务器上储存表情包并且简便得发送
使用效果类似于 @FavStockersBot (但这个bot有最多只能储存50个表情) 效果图如下
![Screenshot_20190930-235536](https://user-images.githubusercontent.com/38450642/65885383-e4f43d00-e3dd-11e9-8c7e-ccdc4c219e88.png)

顺带一提, efb确实是个十分有意思而且有用的项目, 感谢开发

**Comment by blueset** [comment]
> Target repository: `blueset/efb-telegram-master`

感谢建议。

如果有需要更多自定义表情包的需求，建议直接在 @Stickers 处创建个人专用表情包，这样会更加便捷。目前 ETM 没有对表情添加 inline query 支持的计划。
