### ISSUE TITLE
关于 efb 缓存 占用严重

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#72]
不知道efb缓存的清理办法？
有点太占用空间了……
而且长时间不重启服务
会出现各种各样的错误

**Comment by blueset** [comment]
请问您所指的「缓存」是那些文件？

如果在运行时发现了错误，并且确实是 EFB 及其组件造成的，欢迎在相关代码仓库（repositories）依照《贡献指南》提出报告（issue）。

**Comment by shzxm** [comment]
> 请问您所指的“缓存”是那些文件？
> 
> 如果在运行时发现了错误，并且确实是EFB和常规组件造成的，欢迎在相关代码仓库（存储库）按照相应的《贡献指南》提出报告（issue）。

微信从端下载的图片.视频.文件.会一直保存.直到塞满硬盘.
我找不到具体的文件存放位置.
因为会发送到tg.本身就是保存到云端的
所以建议添加 定时清理缓存 的功能
或者方便告知一下.微信下载的这些内容保存的位置
方便删除

**Comment by blueset** [comment]
请提供所使用的 EH Forwarder Bot 及组件的版本。

自 EFB 2 开始，临时存储的文件是由 Python 控制、在操作系统的临时文件路径创建，并在不再使用后进行删除。目前的逻辑中不会长期存储下载到的媒体文件。

**Comment by shzxm** [comment]
> 请提供所使用的EH Forwarder Bot及所有已启用组件的版本。
> 
> 自EFB 2开始，临时存储的文件是由Python控制，在操作系统的临时文件路径创建，并在不再使用后进行删除。目前的逻辑中不会长期存储下载到的媒体文件。

感谢解答.目前已经重新装了....所以版本为止....等再次出现问题.重新提交

**Comment by yEs1do** [comment]
/root/ehForwarderBot/storage/eh_wechat_slave 里的东西全都删掉
