### ISSUE TITLE
Telegram does not show the received image/sticker file in some cases

### ISSUE THREAD

**Issue by catbaron0** [blueset/efb-wechat-slave#74]
This issue is observed when:
- send a gif sticker
- send an image as file

from wechat.

As the result, what Telegram receives would be a file who got a temporary filename without extension name (e.g. `tmpvaqh4fo8`)

<del>I've found where the bug is, and I would submit **two** pr to fix it. (one for efb-wechat-slave, and another for efb-telegram-master) </del>
This issue is just for reference.

I found the latest version has fixed this bug. Orz

Please close me.

**Comment by blueset** [comment]
Thanks for bringing this up. 

For people visiting this issue later, here are the related issues/PRs:
- [etm#71](https://github.com/blueset/efb-telegram-master/issues/71) (issue)
- [etm#72](https://github.com/blueset/efb-telegram-master/pull/72) (PR)
