### ISSUE TITLE
链接到聊天组的用户只能收到消息，不能发送消息，只能收到消息

### ISSUE THREAD

**Issue by yswtrue** [blueset/efb-wechat-slave#77]
### 版本信息
2.0.0b20

### 问题描述
链接到聊天组的用户只能收到消息，不能发送消息

### 重现步骤
在bot里面link一个用户到已建的用户组，然后发送消息，微信实际上没有发出去，但是对方发送消息是可以收到的

**Comment by yswtrue** [comment]
我发现，只要新建群组，然后把efb设置为管理员，link聊天，然后update_info，就可以正常发送和接收了

**Comment by blueset** [comment]
请确保 ETM Telegram Bot 的隐私设置已处于关闭状态，默认开启隐私设置的情况下 Bot 在 Telegram 群组里面只能够收到指令信息。
