### ISSUE TITLE
微信原图 保存文件错误?

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#82]
### 版本信息
EH Forwarder Bot
Version: 2.0.0b20
Python version:
3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b26 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a29 # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述
微信中,接收到的原图文件保存扩展名错误?
具体表现为
![image](https://user-images.githubusercontent.com/9905297/69189039-a155be00-0b58-11ea-866f-aa8d29da236e.png)
文件可以正常打开
![image](https://user-images.githubusercontent.com/9905297/69189084-b6325180-0b58-11ea-82a5-e6ac42e9200e.png)
但是缺失扩展名

### Verbose 日志

</details>

**Comment by blueset** [comment]
Duplicate of blueset/efb-telegram-master#71.
已于 ETM 2.0.0b27 版本修复。
