### ISSUE TITLE
登录二维码只允许被获取一次

### ISSUE THREAD

**Issue by AkazaDorian** [blueset/efb-wechat-slave#83]
由于如题的原因，加上 systemctl 无法正常显示二维码，导致我即使通过打开链接后用摄像头扫描的方式也无法登陆（因为二维码已经被 EFB 获取过一次了），二维码会被直接刷新陷入循环，请问有什么方法可以避免吗？

**Comment by blueset** [comment]
抱歉，没能看明白你的问题。能描述一下不能登陆的具体症状吗？

我个人用 `systemctl`/`journalctl` 管理 EFB，扫描登录目前还没有遇到问题。

**Comment by AkazaDorian** [comment]
@blueset 具体症状是：`systemctl start ehforwarderbot` 启动 EFH 之后，`systemctl status ehforwarderbot` 来获取二维码的地址，然后打开二维码，用手机扫描。在微信上点击登录之后登录窗口消失，但是 EFH 并没有响应，而是在继续刷新二维码。只有通过直接运行 `ehforwarderbot` 并扫描 stdout 的二维码才能成功登录。

**Comment by blueset** [comment]
试一下下面的指令来调出日志？

```
$ journalctl -fu 后台服务名称 -n 100 -o cat
```

**Comment by AkazaDorian** [comment]
想了一下可能是因为二维码刷新太快而我从 systemctl status 获得二维码的速度不够快导致的过期，先关掉好了
