### ISSUE TITLE
希望在第一次登录时能直接将二维码发送至主端

### ISSUE THREAD

**Issue by rhjdvsgsgks** [blueset/efb-wechat-slave#87]
### 版本信息

2.0.0a34

### 问题描述

使用systemd重启efb时，因为二维码不能在`systemctl status`中显示，每次登录都需要把链接复制到浏览器中打开，再扫描二维码，经常出现因为二维码过期导致无法登录的情况(具体表现为扫描二维码后微信和efb都没有反应，就和没扫一样，但微信也没有提示二维码过期)，这个问题是最近才出现的，我现在是先自己启动efb，直接扫描二维码成功后才使用systemd启动efb，这样才能登录成功，因此我希望能(添加个选项来)把二维码发送至主端，这样能更快的扫描上二维码，而且也不用每次重启都要开ssh了

### 重现步骤

使用`systemctl restart efb.service`重启efb

### Verbose 日志
暂无

**Comment by blueset** [comment]
这样的设计是处于框架结构的考虑，目前没有计划让主端在从端之前初始化。相关的设计思路以及讨论请参见 [EFB#148](https://github.com/blueset/ehForwarderBot/pull/148)。

关于使用 `systemd` 管理 EFB 进程时查看完整二维码输出的情况，建议使用 `journalctl` 工具来查看完整的二维码内容。

**Comment by rhjdvsgsgks** [comment]
在journalctl中二维码也无法显示，和systemd效果一样

**Comment by blueset** [comment]
希望能提供一下相关指令、使用的终端程序、以及终端显示截图。

这边使用 `journalctl` 显示是没有问题的。

**Comment by rhjdvsgsgks** [comment]
```systemctl restart ehforwarderbot-wechat.service```
```journalctl -u ehforwarderbot-wechat.service```
使用的juicessh和termux+ssh均无法正常显示二维码
juicessh终端类型为xterm-256color，可以正常显示256色
termux+ssh能显示真彩色
截图如下
![_20191218_233820](https://user-images.githubusercontent.com/26178113/71100343-79b73d00-217a-11ea-9ff9-8ebb3b368445.JPG)

**Comment by blueset** [comment]
有可能是 `journalctl` 默认模式吞掉了 ANSI Escape Sequence。试试更换一下输出模式？（比如 `journalctl -u ehforwarderbot-wechat.service -o cat`）

**Comment by rhjdvsgsgks** [comment]
感谢，现在二维码能显示了
