### ISSUE TITLE
微信频繁掉线

### ISSUE THREAD

**Issue by kettly1260** [blueset/efb-wechat-slave#88]
### 版本信息

您正在使用 EFB Telegram 主端 2.0.0b36，运行于默认配置档案与实例、EFB 版本 2.0.0b23。
已激活 1 个从端：
- 💬 WeChat Slave (blueset.wechat, 2.0.0a35)

### 问题描述

slave更新到最新版之后在半夜会自动登出，之后若重新扫码登录，也无法正常登录，手机端确认登录之后依旧会提示已退出登录，要重新扫码。删除wxpy.pkl之后可以正常登录，但半夜又会自动退出。

### 重现步骤

tg提示重新扫码登录，点击扫码登录可复现

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
程序在提示重新扫码的时候未出现任何提示



```
 
</details>

**Comment by blueset** [comment]
近期版本中没有对登陆和轮询部分的代码进行更改。请检查所使用的服务器于夜间是否有（至微信网页版）网络连接中断或部分中断的现象。

**Comment by kettly1260** [comment]
> 近期版本中没有对登陆和轮询部分的代码进行更改。请检查所使用的服务器于夜间是否有（至微信网页版）网络连接中断或部分中断的现象。

该问题并不出现在更新版本以前。之前我用的29的版本没有这个问题
在tg讨论群内已有好几个和我相同情况的人出现

**Comment by gary02** [comment]
也是半夜掉线， 是不是微信那边做了手脚

**Comment by zhigang1992** [comment]
很久都没有更新过，最近好几天都是半夜掉线了

**Comment by gadflysu** [comment]
我也遇到「夜间掉线」这个问题，发生时间在大约在两点到五点之间，后半夜更加频繁。但是

> [之后若重新扫码登录，也无法正常登录，手机端确认登录之后依旧会提示已退出登录，要重新扫码](https://github.com/blueset/efb-wechat-slave/issues/88#issue-540014181)

这个「难以重新登录」的问题在我这里和「夜间掉线」的相关性不大，这是更早些时候掉线就已经遇到的状况。既然没有改动过代码，**估计还是微信那边的问题**。然而处理方法同样是删除 `wxpy.pkl` 后重启。

另外注意到重新登录时若保持 EFB 和微信客户端在同一国家或地区的 IP 对情况有所改善，能重新登录。

**Comment by zhigang1992** [comment]
有一个发现是如果当天晚上微信时候到比较晚的时候的话，那么这个登出的时间会更晚。
比如很早就睡了，那么在2点左右会断开，如果12点还在发消息，那么可能到5点多才登出

**Comment by blueset** [comment]
在支持群组里面[调查了一下][1]，看起来没有掉线的情况比较多。鉴于这个现象，以及最近一直没有修改过鉴权、轮询方面的代码，初步判定是网页版微信方面的行为。对于此类问题，很遗憾 EWS 无能为力，只能静待其服务修复。

![image](https://user-images.githubusercontent.com/553831/71400838-ea6ec580-2662-11ea-9abc-b4079e5024c9.png)

[1]: https://t.me/c/1083959736/63064

**Comment by davidlauhn** [comment]
同样的问题，好郁闷

**Comment by blueset** [comment]
隔壁其他网页版微信相关项目也有报告相关问题：
- [itchat#888](https://github.com/littlecodersh/ItChat/issues/888)

**Comment by zhigang1992** [comment]
我重装了手机端的微信，好像就好了～ @blueset

**Comment by Kingbultsea** [comment]
> 我重装了手机端的微信，好像就好了～ @blueset

现在怎么样啦，那么神奇

**Comment by zhigang1992** [comment]
已经一周多没有登出了

**Comment by kettly1260** [comment]
不知道微信是怎么控制的。我两个微信，同样的系统和网络环境，一个正常登录不掉线，另一个每晚掉线还要删除wxpy.pkl之后才可以正常登录 @blueset @zhigang1992

**Comment by Kingbultsea** [comment]
> 已经一周多没有登出了

请问微信版本号是多少呀。os 还是 安卓？

**Comment by zhigang1992** [comment]
@Kingbultsea  iOS 7.0.9

**Comment by ZYCzyc19970105** [comment]
> > 已经一周多没有登出了
> 
> 请问微信版本号是多少呀。os 还是 安卓？

又看到你了

**Comment by blueset** [comment]
Closing this issue as stale.
