### ISSUE TITLE
微信ios最新版支持指定回复了.好像用的是引用的接口

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#89]
微信ios最新版支持指定回复了.好像用的是引用的接口
不知道能不能做到efb里边.指定回复

**Comment by blueset** [comment]
目前 EFB 微信从端（EWS）__仅支持微信网页版所支持的功能以及消息类型__<sup>[(1)]</sup>。在网页版微信支持指定回复消息内容之前（估计这辈子是没希望了），EWS 无法调用原生接口进行消息引用。

如果有生之年微信团队<del>幡然悔悟</del>给网页版加上了这个功能，可以在重开这个 issue  并留言。

[(1)]: https://github.com/blueset/efb-wechat-slave#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98
