### ISSUE TITLE
分享展示为不支持的类型

### ISSUE THREAD

**Issue by wolfsilver** [blueset/efb-wechat-slave#91]
https://github.com/blueset/efb-wechat-slave/blob/f68b10dcf8999b2c2b2192d22acb30537fcf524a/efb_wechat_slave/slave_message.py#L493-L497

这个`if node:`判断有时候有问题，会导致有些分享变成不支持的类型
貌似要用`if node is not None:`

**Comment by blueset** [comment]
Fixed in e8c5b53.

已修复，待发布。

**Comment by blueset** [comment]
已于 2.0.0a36 发布。
