### ISSUE TITLE
正则引用错误

### ISSUE THREAD

**Issue by wolfsilver** [blueset/efb-wechat-slave#95]
https://github.com/blueset/efb-wechat-slave/blob/8748051ac1c7b011c9b7902a9879e020261f5acb/efb_wechat_slave/slave_message.py#L222-L226
应该是
```
elif any(i in msg.text for i in self.CHAT_AND_MEMBER_UPDATE_PATTERNS): 
```

**Comment by blueset** [comment]
感谢，已修复。
