### ISSUE TITLE
支持微信内置动画表情

### ISSUE THREAD

**Issue by yi-ji** [blueset/efb-wechat-slave#98]
### 版本信息

ehforwarderbot      2.0.0b15
efb-wechat-slave    2.0.0a18

### 问题描述

当微信收到内置动画表情（即微信官方上架的表情包）时，ehforwarderbot只转发以下消息：

> (unsupported)
[Failed to download the sticker, please check your phone.]

可以考虑将微信动画表情转换为gif格式转发，或者只保留第一帧的jpg格式。

### 重现步骤

同上。

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by blueset** [comment]
由于版权原因，网页版微信无法收到此类表情包。很遗憾对此我们无能为力。

如后来微信网页版增加了对此类表情对支持，请在此留言。谢谢。
